paths:
  /products:
    get:
      summary: Obtener productos con paginación y filtros
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
        - name: page
          in: query
          schema:
            type: integer
        - name: filter
          in: query
          schema:
            type: string
        - name: ord
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Lista de productos
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Error interno del servidor